### ISSUE TITLE
Build the Website Home Page

### ISSUE THREAD

**Issue by loan-mgt** [InstagramArchive/web#1]
### Description:
We need to create the website's home page using HTML and Tailwind CSS. This issue is to track the progress and work required to replicate the provided model for the home page.

### Task:

**Objective:** Build the website home page following the provided model.

**Note:** The "start" button must glow when hovered 

**Model Reference:** ![Model](https://github.com/InstagramArchive/web/assets/37497007/541b8e8a-fb92-499f-ae26-ab2566dbafd4)

**Comment by dilini-liyanage** [comment]
Hi, I would like to work on this issue. Can you assign this to me?

**Comment by loan-mgt** [comment]
@dilini-liyanage There you go! 😊

**Comment by dilini-liyanage** [comment]
Thank you for assigning me

**Comment by loan-mgt** [comment]
Closed by #2
